In [1]:
from pathlib import Path
from retinaface import RetinaFace
import cv2
import os

I0000 00:00:1790653851.991631 1162160 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
I0000 00:00:1790653851.992051 1162160 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1790653852.024028 1162160 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI AVX512_BF16 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
I0000 00:00:1790653853.327212 1162160 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONE

In [2]:
input_folder = "raw_data/images"
output_folder = "raw_data/extracted_faces"

#### **Extract Faces**

In [3]:
def extract_faces(images_folder=False, output_folder=False):
    for image_file in Path(images_folder).glob("*"):
        if image_file.suffix.lower() not in [".jpg", ".jpeg", ".png", ".webp"]:
            continue

        try:
            faces = RetinaFace.extract_faces(
                img_path=str(image_file),
                align=True
            )

            for idx, face in enumerate(faces):
                face = cv2.cvtColor(face, cv2.COLOR_RGB2BGR)

                filename = f"{image_file.stem}_face_{idx+1}.jpg"
                cv2.imwrite(
                    os.path.join(output_folder, filename),
                    face
                )

            print(f"{image_file.name}: {len(faces)} faces")

        except Exception as e:
            print(f"Error: {image_file.name} -> {e}")

    return False

In [4]:
# Extract faces
extract_faces(images_folder=input_folder, output_folder=output_folder)

E0000 00:00:1790653879.995096 1162160 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)


IMG_5331.jpg: 1 faces
IMG_5347.jpg: 1 faces
IMG_5320.jpg: 1 faces
IMG_5327.jpg: 1 faces
IMG_5302.jpg: 1 faces
IMG_5341.jpg: 1 faces
IMG_5306.jpg: 1 faces
IMG_5307.jpg: 1 faces
IMG_5350.jpg: 1 faces
IMG_5334.jpg: 1 faces
IMG_5308.jpg: 1 faces
IMG_5305.jpg: 1 faces
IMG_5336.jpg: 1 faces
IMG_5329.jpg: 1 faces
IMG_5314.jpg: 1 faces
IMG_5317.jpg: 1 faces
IMG_5337.jpg: 1 faces
IMG_5339.jpg: 1 faces
IMG_5340.jpg: 1 faces
IMG_5342.jpg: 1 faces
IMG_5333.jpg: 1 faces
IMG_5321.jpg: 1 faces
IMG_5349.jpg: 1 faces
IMG_5312.jpg: 1 faces
IMG_5326.jpg: 1 faces
IMG_5313.jpg: 1 faces
IMG_5315.jpg: 1 faces
IMG_5348.jpg: 1 faces
IMG_5304.jpg: 1 faces
IMG_5318.jpg: 1 faces
IMG_5319.jpg: 1 faces
IMG_5325.jpg: 1 faces
IMG_5311.jpg: 1 faces
IMG_5345.jpg: 1 faces
IMG_5335.jpg: 1 faces
IMG_5351.jpg: 1 faces
IMG_5316.jpg: 1 faces
IMG_5323.jpg: 1 faces
IMG_5310.jpg: 1 faces
IMG_5303.jpg: 1 faces
IMG_5332.jpg: 2 faces
IMG_5344.jpg: 1 faces
IMG_5352.jpg: 1 faces
IMG_5338.jpg: 1 faces
IMG_5343.jpg: 1 faces
IMG_5328.j

False

#### **Face size**

In [5]:
from retinaface import RetinaFace
import cv2


def calculate_face_size(file_path=False):
    # image = cv2.imread("Datasets/group_photo.jpg")

    if not file_path:
        return False
    
    image = cv2.imread(file_path)

    faces = RetinaFace.detect_faces(image)

    print(f"File: {file_path}")
    
    for face_id, face_data in faces.items():
        x1, y1, x2, y2 = face_data["facial_area"]

        width = x2 - x1
        height = y2 - y1

        print(f"Face Size: {width} x {height}")

In [6]:
files = ['Datasets/group_photo.jpg', 'Datasets/multi_face_output.jpg', 'Datasets/obama.jpg', 'Datasets/Tejrit.jpg',
         'Datasets/vimala.jpg']

for idx in files:
    calculate_face_size(file_path=idx)

File: Datasets/group_photo.jpg
Face Size: 184 x 270
Face Size: 209 x 279
Face Size: 204 x 180
Face Size: 247 x 309
Face Size: 151 x 194
File: Datasets/multi_face_output.jpg
Face Size: 435 x 499
Face Size: 399 x 535
Face Size: 357 x 485
Face Size: 407 x 498
File: Datasets/obama.jpg
Face Size: 229 x 347
File: Datasets/Tejrit.jpg
File: Datasets/vimala.jpg
Face Size: 1086 x 1515


In [7]:
# Using OpenCV Haar Cascade

import cv2

img = cv2.imread("Datasets/group_photo.jpg")
img = cv2.imread("Datasets/multi_face_output.jpg")
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

face_cascade = cv2.CascadeClassifier(
    cv2.data.haarcascades +
    "haarcascade_frontalface_default.xml"
)

faces = face_cascade.detectMultiScale(
    gray,
    scaleFactor=1.1,
    minNeighbors=5
)

for (x, y, w, h) in faces:
    print(f"Face Size: {w} x {h}")

Face Size: 27 x 27
Face Size: 26 x 26
Face Size: 52 x 52
Face Size: 64 x 64
Face Size: 57 x 57
Face Size: 76 x 76
Face Size: 64 x 64
Face Size: 68 x 68
Face Size: 60 x 60
Face Size: 77 x 77
Face Size: 72 x 72
Face Size: 74 x 74
Face Size: 73 x 73
Face Size: 72 x 72
Face Size: 73 x 73
Face Size: 80 x 80
Face Size: 80 x 80
Face Size: 27 x 27
Face Size: 74 x 74
Face Size: 78 x 78
Face Size: 86 x 86
Face Size: 458 x 458
Face Size: 442 x 442
Face Size: 64 x 64
Face Size: 67 x 67
Face Size: 61 x 61
Face Size: 82 x 82
Face Size: 446 x 446
Face Size: 72 x 72
Face Size: 78 x 78
Face Size: 409 x 409
Face Size: 27 x 27
Face Size: 34 x 34
Face Size: 85 x 85


#### **Generate ArcFace Embeddings from Face Images**

The InsightFace/ArcFace pipeline exposes normalized embeddings that can be directly compared with cosine similarity.

#### **Save Embeddings to Numpy Files**

In [49]:
from pathlib import Path

def check_path(path=False):
    path_obj = Path(path)

    if path_obj.is_dir():
        # print("It is a directory path.")
        return 2
    elif path_obj.is_file():
        # print("It is a full file path.")
        return 1
    else:
        # print("The path does not exist.")
        return 0

def create_embedding_image(app=False, save_emb=True, image_file_path=False, embeddings_dir=False):
    image = cv2.imread(str(image_file_path))
    
    faces = app.get(image)

    if not faces:
        return False

    embedding = faces[0].embedding

    if save_emb:
        np.save(embeddings_dir / f"{image_file_path.stem}.npy", embedding)
        print(f"Saved {image_file_path.stem}.npy")

    return embedding

def create_embeddings(save_emb=True, faces_dir=False, embeddings_dir=False):
    app = FaceAnalysis(name="buffalo_l", providers=["CPUExecutionProvider"])

    app.prepare(ctx_id=0)

    faces_dir = Path(faces_dir)
    embeddings_dir = Path(embeddings_dir)

    embeddings_dir.mkdir(exist_ok=True)

    temp = check_path(faces_dir)

    if temp==1:
        embedding = create_embedding_image(app=app, save_emb=save_emb, image_file_path=faces_dir, embeddings_dir=embeddings_dir)
    elif temp==2:
        for image_file in faces_dir.glob("*.jpg"):
            embedding = create_embedding_image(app=app, save_emb=save_emb, image_file_path=image_file, 
                                               embeddings_dir=embeddings_dir)
    else:
        embedding = False

    return embedding

In [52]:
# create_embeddings(save_emb=False, faces_dir="raw_data/extracted_faces/IMG_5302_face_1", embeddings_dir=embeddings_dir)
embedding = create_embeddings(save_emb=True, faces_dir="raw_data/extracted_faces/IMG_5302_face_1.jpg", 
                              embeddings_dir=embeddings_dir)

Saved IMG_5302_face_1.npy


In [51]:
import cv2
import numpy as np
from pathlib import Path
from insightface.app import FaceAnalysis

faces_dir = "raw_data/extracted_faces"
embeddings_dir = "raw_data/embeddings"

embedding = create_embeddings(faces_dir=faces_dir, embeddings_dir=embeddings_dir)

Saved IMG_5333_face_1.npy
Saved IMG_5316_face_1.npy
Saved IMG_5332_face_2.npy
Saved IMG_5313_face_1.npy
Saved IMG_5339_face_1.npy
Saved IMG_5304_face_1.npy
Saved IMG_5335_face_1.npy
Saved IMG_5311_face_1.npy
Saved IMG_5348_face_1.npy
Saved IMG_5327_face_1.npy
Saved IMG_5334_face_1.npy
Saved IMG_5323_face_1.npy
Saved IMG_5331_face_1.npy
Saved IMG_5344_face_1.npy
Saved IMG_5321_face_1.npy
Saved IMG_5330_face_1.npy
Saved IMG_5347_face_1.npy
Saved IMG_5341_face_1.npy
Saved IMG_5303_face_1.npy
Saved IMG_5317_face_1.npy
Saved IMG_5336_face_1.npy
Saved IMG_5340_face_1.npy
Saved IMG_5343_face_1.npy
Saved IMG_5324_face_1.npy
Saved IMG_5332_face_1.npy
Saved IMG_5307_face_1.npy
Saved IMG_5306_face_1.npy
Saved IMG_5342_face_1.npy
Saved IMG_5349_face_1.npy
Saved IMG_5345_face_1.npy
Saved IMG_5320_face_1.npy
Saved IMG_5325_face_1.npy
Saved IMG_5338_face_1.npy
Saved IMG_5310_face_1.npy
Saved IMG_5328_face_1.npy
Saved IMG_5318_face_1.npy
Saved IMG_5337_face_1.npy
Saved IMG_5312_face_1.npy
Saved IMG_53

#### **Compare Two Faces**

ArcFace embeddings are designed for cosine-similarity matching in recognition, search, and watchlist workflows.

In [60]:
def compare_faces(face_emb1=False, face_emb2=False):
    if isinstance(face_emb1, str):
        face_emb1 = np.load(face_emb1)
    if isinstance(face_emb2, str):
        face_emb2 = np.load(face_emb2)
    
    # Cosine Similarity
    similarity = np.dot(
        face_emb1 / np.linalg.norm(face_emb1),
        face_emb2 / np.linalg.norm(face_emb2)
    )

    print(f"Similarity: {similarity:.4f}")

    if similarity > 0.5:
        print("Same Person")
        return True
    else:
        print("Different Person")
        return False

In [65]:
face_emb1 = "raw_data/embeddings/IMG_5315_face_1.npy"
face_emb2 = "raw_data/embeddings/IMG_5315_face_1.npy"

compare_faces(face_emb1=face_emb1, face_emb2=face_emb2)

Similarity: 1.0000
Same Person


True

In [66]:
compare_faces(face_emb1=embedding, face_emb2=face_emb2)

Similarity: -0.0069
Different Person


False

#### **How to use FAISS**

Step 1: Generate ArcFace Embeddings

In [67]:
import faiss
import numpy as np
from pathlib import Path

In [68]:
# Step 2: Create a FAISS Index
def create_faiss_index(DIMENSION = 512):
    # Cosine similarity requires normalized vectors
    index = faiss.IndexFlatIP(DIMENSION)

    print(index.ntotal)

    return index

In [ ]:
def load_embedding(file_path=False):
    embedding = np.array([
            np.load(file_path),
        ], dtype=np.float32)
    
    # Normalize
    faiss.normalize_L2(embedding)

    return embedding

def add_embeddings(faiss_index=False, file_path=False):    
    embedding = load_embedding(file_path=file_path)

    # index.add(embedding)
    faiss_index.add(embedding)

    return True

In [70]:
dir_path = Path("raw_data/embeddings")

# create FAISS Index
faiss_index = create_faiss_index()

# Add Embeddings
emb_files = [f for f in dir_path.rglob("*.npy") if f.is_file()]

for file in emb_files:
    print(file)  # Prints the full path relative to dir_path
    
    add_embeddings(faiss_index=faiss_index, file_path=file)
    
print(faiss_index.ntotal)

0
raw_data/embeddings/IMG_5350_face_1.npy
raw_data/embeddings/IMG_5332_face_2.npy
raw_data/embeddings/IMG_5304_face_1.npy
raw_data/embeddings/IMG_5330_face_1.npy
raw_data/embeddings/IMG_5339_face_1.npy
raw_data/embeddings/IMG_5348_face_1.npy
raw_data/embeddings/IMG_5328_face_1.npy
raw_data/embeddings/IMG_5323_face_1.npy
raw_data/embeddings/IMG_5326_face_1.npy
raw_data/embeddings/IMG_5333_face_1.npy
raw_data/embeddings/IMG_5305_face_1.npy
raw_data/embeddings/IMG_5315_face_1.npy
raw_data/embeddings/IMG_5341_face_1.npy
raw_data/embeddings/IMG_5313_face_1.npy
raw_data/embeddings/IMG_5332_face_1.npy
raw_data/embeddings/IMG_5349_face_1.npy
raw_data/embeddings/IMG_5314_face_1.npy
raw_data/embeddings/IMG_5334_face_1.npy
raw_data/embeddings/IMG_5308_face_1.npy
raw_data/embeddings/IMG_5337_face_1.npy
raw_data/embeddings/IMG_5325_face_1.npy
raw_data/embeddings/IMG_5346_face_1.npy
raw_data/embeddings/IMG_5329_face_1.npy
raw_data/embeddings/IMG_5317_face_1.npy
raw_data/embeddings/IMG_5343_face_1.np

In [119]:
def search_face(faiss_index=False, search_emb_path=False, search_img_path=False, threshold=0.6):
    if search_img_path:
        # query = create_embedding(file_path=search_img_path)
        # query = create_embedding_image(save_emb=False, faces_dir=search_img_path, embeddings_dir=embeddings_dir)
        query = create_embeddings(save_emb=False, faces_dir=search_img_path, embeddings_dir=embeddings_dir)
        # query = np.array(
        #             create_embeddings(save_emb=True, faces_dir=search_img_path, embeddings_dir=embeddings_dir),
        #             dtype=np.float32
        #             )
        query = query[np.newaxis, :]
        faiss.normalize_L2(query)
    else:
        query = np.array(
            load_embedding(file_path=search_emb_path),
            dtype=np.float32
            )
        # query = np.array(
        #     [search_emb_path],
        #     dtype=np.float32
        # )

        faiss.normalize_L2(query)

    distances, indices = faiss_index.search(
        query,
        5
    )

    score = float(distances[0][0])
    idx = int(indices[0][0])

    if score >= threshold:
        return indices, distances

    return None, distances

In [120]:
# Search face using embeding
search_face(faiss_index=faiss_index, search_emb_path='raw_data/embeddings/IMG_5302_face_1.npy')

(array([[30, 33,  2, 10, 42]]),
 array([[1.       , 0.9774196, 0.9682908, 0.9636948, 0.9416403]],
       dtype=float32))

In [121]:
# Search face using raw image
search_face(faiss_index=faiss_index, search_img_path='raw_data/extracted_faces/IMG_5302_face_1.jpg')

(array([[30, 33,  2, 10, 42]]),
 array([[1.       , 0.9774196, 0.9682908, 0.9636948, 0.9416403]],
       dtype=float32))

#### **Step 4: Store Person Mapping**

FAISS stores vectors only.

Keep a mapping:

In [62]:
person_mapping = {
    0: {
        "person_id": 101,
        "name": "John"
    },
    1: {
        "person_id": 102,
        "name": "Alice"
    },
}

#### **Step 6: Match Decision**

| Similarity | Meaning                  |
| ---------- | ------------------------ |
| > 0.80     | Very likely same person  |
| 0.65–0.80  | Possible match           |
| < 0.60     | Usually different person |


In [69]:
best_score = distances[0][0]
best_idx = indices[0][0]

if best_score > 0.6:
    print("Known Person")
else:
    print("Unknown Person")

Known Person


#### **Step 7: Save/Load FAISS Index**

In [122]:
faiss.write_index(
    faiss_index,
    "Datasets/faces.index"
)

In [123]:
faiss_index = faiss.read_index(
    "Datasets/faces.index"
)

In [124]:
# Search face using raw image
search_face(faiss_index=faiss_index, search_img_path='raw_data/extracted_faces/IMG_5302_face_1.jpg')

(array([[30, 33,  2, 10, 42]]),
 array([[1.       , 0.9774196, 0.9682908, 0.9636948, 0.9416403]],
       dtype=float32))

In [125]:
# Search face using embeding
search_face(faiss_index=faiss_index, search_emb_path='raw_data/embeddings/IMG_5302_face_1.npy')

(array([[30, 33,  2, 10, 42]]),
 array([[1.       , 0.9774196, 0.9682908, 0.9636948, 0.9416403]],
       dtype=float32))